<#
  cronsmith - one-click DOCKER runner for Windows (PowerShell). Mirror of run-docker.sh.

    .\run-docker.ps1           [-n N] [-e M]   build images & start the stack ('up' is optional)
    .\run-docker.ps1 down                       stop & remove (keeps the H2 data volumes)
    .\run-docker.ps1 logs [scheduler-1|cronflower|executor-1]   tail all logs, or one service

  -n  number of scheduler (server) nodes   (default 1)
  -e  number of executor (client) nodes    (default 0 = none)

  Store is always the embedded H2 file; edit conf\scheduler.properties for a real (shared) DB.
  Ports on the host: schedulers 19090.. . web console 7200 . executors random 50000-60000.

  If scripts are blocked, run:  powershell -ExecutionPolicy Bypass -File .\run-docker.ps1 -n 2 -e 1
#>
param(
  [Parameter(Position = 0)][string]$Action = 'up',
  [Parameter(Position = 1)][string]$Svc = '',
  [int]$n = 1,
  [int]$e = 0
)

. "$PSScriptRoot\_build.ps1"

$ComposeFile   = Join-Path $Here 'docker-compose.generated.yml'
$Project       = 'cronsmith'
$SchedBasePort = if ($env:SCHED_BASE_PORT) { [int]$env:SCHED_BASE_PORT } else { 19090 }
$WebPort       = if ($env:WEB_PORT)        { [int]$env:WEB_PORT }        else { 7200 }
$SpreaderPort  = if ($env:SPREADER_PORT)   { [int]$env:SPREADER_PORT }   else { 22000 }

function Peers-Csv([int]$nodes) { (1..$nodes | ForEach-Object { "scheduler-$_" }) -join ',' }

function Generate-Compose([int]$nodes, [int]$execs, [int[]]$execPorts) {
  $L = New-Object System.Collections.Generic.List[string]
  $L.Add('# GENERATED by run-docker.ps1 - edit the script, not this file.')
  $L.Add('services:')
  $peers = Peers-Csv $nodes
  for ($i = 1; $i -le $nodes; $i++) {
    $port = $SchedBasePort + $i - 1
    $json = '{"server":{"port":8080},"spring":{"spreader":{"port":' + $SpreaderPort + ',"ip-addresses":"' + $peers + '"}}}'
    $L.Add("  scheduler-${i}:")
    $L.Add('    image: cronsmith-scheduler:local')
    $L.Add('    environment:')
    $L.Add("      SPRING_APPLICATION_JSON: '$json'")
    $L.Add('      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/config/scheduler.properties')
    $L.Add('    volumes:')
    $L.Add('      - ./conf/scheduler.properties:/config/scheduler.properties:ro')
    $L.Add("      - sched-data-${i}:/data")
    $L.Add("    ports: [`"${port}:8080`"]")
    $L.Add('    healthcheck:')
    $L.Add('      test: ["CMD","sh","-c","wget -qO- http://localhost:8080/actuator/health | grep -q UP"]')
    $L.Add('      interval: 5s')
    $L.Add('      timeout: 3s')
    $L.Add('      retries: 30')
    $L.Add('      start_period: 20s')
    $L.Add('    networks: [cnet]')
  }
  # cronflower web console - Node static server that proxies /cronsmith + /actuator to scheduler-1.
  $L.Add('  cronflower:')
  $L.Add('    image: cronflower:local')
  $L.Add('    container_name: cronflower')
  $L.Add('    environment:')
  $L.Add('      SCHEDULER_URL: http://scheduler-1:8080')
  $L.Add("    ports: [`"${WebPort}:80`"]")
  $L.Add('    depends_on:')
  $L.Add('      scheduler-1: { condition: service_started }')
  $L.Add('    networks: [cnet]')
  for ($i = 1; $i -le $execs; $i++) {
    $port = $execPorts[$i - 1]
    $ejson = '{"server":{"port":8080},"spring":{"application":{"name":"demo-executor-' + $i + '"}},"cronsmith":{"client":{"server-urls":"http://scheduler-1:8080"}}}'
    $L.Add("  executor-${i}:")
    $L.Add('    image: cronsmith-executor:local')
    $L.Add('    environment:')
    $L.Add("      SPRING_APPLICATION_JSON: '$ejson'")
    $L.Add("    ports: [`"${port}:8080`"]")
    $L.Add('    depends_on:')
    $L.Add('      scheduler-1: { condition: service_started }')
    $L.Add('    networks: [cnet]')
  }
  $L.Add('networks: { cnet: {} }')
  $L.Add('volumes:')
  for ($i = 1; $i -le $nodes; $i++) { $L.Add("  sched-data-${i}:") }
  Set-Content -Path $ComposeFile -Value $L -Encoding ascii
}

function Do-Up {
  Check-Prereqs $true
  Check-Capacity $n $e (Docker-MemGb) 'Docker engine RAM'
  Build-Backend
  Stage-Jars
  Build-FrontendDist
  $webDist = Join-Path $Here 'web-dist'
  if (Test-Path $webDist) { Remove-Item $webDist -Recurse -Force }
  New-Item -ItemType Directory -Force -Path $webDist | Out-Null
  Copy-Item (Join-Path $Frontend 'dist\cronflower\browser\*') $webDist -Recurse -Force

  # Build each image once, up front (several scheduler services share one image tag).
  Write-Host '>> building images'
  & docker build -q -f (Join-Path $Here 'Dockerfile.server') -t cronsmith-scheduler:local $Here
  & docker build -q -f (Join-Path $Here 'Dockerfile.web')    -t cronflower:local $Here
  if ($e -gt 0) { & docker build -q -f (Join-Path $Here 'Dockerfile.executor') -t cronsmith-executor:local $Here }

  # Pre-pick random free host ports for executors so the compose and the summary agree.
  $execPorts = @(); $used = @()
  for ($i = 1; $i -le $e; $i++) { $p = Get-FreePort $used; $used += $p; $execPorts += $p }

  Write-Host ">> generating compose for $n scheduler node(s), $e executor(s)"
  Generate-Compose $n $e $execPorts

  & docker compose -p $Project -f $ComposeFile up -d
  Write-Host ''
  Write-Host 'cronsmith is up (docker):'
  Write-Host "  console    : http://localhost:$WebPort"
  Write-Host "  schedulers : $n node(s) on :$SchedBasePort..$($SchedBasePort + $n - 1)   (H2 file)"
  if ($e -gt 0) { Write-Host "  executors  : $e node(s) on random host ports: $($execPorts -join ' ')" }
  Write-Host "  real DB?   : edit conf\scheduler.properties (MySQL/PostgreSQL) - mounted into every node; default is H2"

  $names = if ($n -gt 1) { "scheduler-1..$n" } else { 'scheduler-1' }
  $names += ' | cronflower'
  if ($e -eq 1)     { $names += ' | executor-1' }
  elseif ($e -gt 1) { $names += " | executor-1..$e" }
  Write-Host "  tail a log : .\run-docker.ps1 logs [name]   (name: $names; empty = all)"
  Write-Host "  stop all   : .\run-docker.ps1 down"
}

switch ($Action) {
  'down' {
    if (Test-Path $ComposeFile) { & docker compose -p $Project -f $ComposeFile down }
    else { & docker compose -p $Project down }
  }
  'logs' {
    if ($Svc) { & docker compose -p $Project -f $ComposeFile logs -f --tail=100 $Svc }
    else      { & docker compose -p $Project -f $ComposeFile logs -f --tail=100 }
  }
  'up'    { Do-Up }
  default { Do-Up }
}
